### ISSUE TITLE
議事録スレッド

### ISSUE THREAD

**Issue by habakan** [katsu1110/NNNS#3]
毎回のモブプロ会の議事録管理用スレッド（仮置）  
モブプロ時はhackmdなどでリアルタイムで議事録作成  
今後はwikiとかで管理とか?

**Comment by habakan** [comment]
# 2022/3/8

## 今後の運用方針について確認
- Notebook or Script?
    - 変数の確認などであれば、ノートブックのほうがやりやすい？
    - ログの記録など、スクリプトのほうがいい場合がでてきたら、そちらに徐々に移行するでもいいかも
    - Notebookが差分管理・保守運用は大変そう
    - ひとまずNotebookで！
- Legacy or Super Massive?
    - headの先頭100行を利用してモブプロではコーディング
    - 実際の学習、validationは両方採用？
    - Diganosticsは運営公式のやつをみたいのでsuper massiveに
- DL Framework
    - 正直誰か一人でも知っていれば何を使ってもよさそう
    - kerasのほうがチュートリアルが豊富？
    - define by runを活かすならpytorch
    - tpuに対応していることを考慮するなら、keras
    - keras start
- その他モブプロ会でやりたいこと
    - 1回休んでも再開できるような体制に
        - 毎回の議事録を共有
    - live testはしたい
    - metricsは設計し直したい
        - nn単体でxgbに勝つのはきつそう→mmcなどを指標にする？
- 何を実装する？
    - ひとまずbaselineを作成してから検討
- 時間どうするか？
    - 次回水曜日で

**Comment by katsu1110** [comment]
@habakan さんありがとうございます！次回以降は自分がwikiに議事録取ります！

**Comment by habakan** [comment]
> @habakan さんありがとうございます！次回以降は自分がwikiに議事録取ります！

いえいえ！  
wikiに移行したらこちらcloseします！

**Comment by katsu1110** [comment]
https://github.com/katsu1110/NNNS/wiki/NNNS-%231-(2022-03-08-Tue.-21:00~)

とりあえずWikiにも転載させていただきました。この形式で大丈夫ですかね？

**Comment by habakan** [comment]
大丈夫です！ ありがとうございます！
